/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type BadRequestResponseImsxCodeMinorField = {
  imsxCodeMinorFieldName?: "TargetEndSystem" | undefined;
  imsxCodeMinorFieldValue?: "invaliddata" | undefined;
};

export type BadRequestResponseImsxCodeMinor = {
  imsxCodeMinorField: Array<BadRequestResponseImsxCodeMinorField>;
};

export type BadRequestResponseErrorData = {
  imsxCodeMajor: "failure";
  imsxSeverity: "error";
  imsxDescription: string;
  imsxCodeMinor: BadRequestResponseImsxCodeMinor;
};

export class BadRequestResponseError extends Error {
  imsxCodeMajor: "failure";
  imsxSeverity: "error";
  imsxDescription: string;
  imsxCodeMinor: BadRequestResponseImsxCodeMinor;

  /** The original data that was passed to this error instance. */
  data$: BadRequestResponseErrorData;

  constructor(err: BadRequestResponseErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.imsxCodeMajor = err.imsxCodeMajor;
    this.imsxSeverity = err.imsxSeverity;
    this.imsxDescription = err.imsxDescription;
    this.imsxCodeMinor = err.imsxCodeMinor;

    this.name = "BadRequestResponseError";
  }
}

/** @internal */
export const BadRequestResponseImsxCodeMinorField$inboundSchema: z.ZodType<
  BadRequestResponseImsxCodeMinorField,
  z.ZodTypeDef,
  unknown
> = z.object({
  imsx_codeMinorFieldName: z.literal("TargetEndSystem").optional(),
  imsx_codeMinorFieldValue: z.literal("invaliddata").optional(),
}).transform((v) => {
  return remap$(v, {
    "imsx_codeMinorFieldName": "imsxCodeMinorFieldName",
    "imsx_codeMinorFieldValue": "imsxCodeMinorFieldValue",
  });
});

/** @internal */
export type BadRequestResponseImsxCodeMinorField$Outbound = {
  imsx_codeMinorFieldName: "TargetEndSystem";
  imsx_codeMinorFieldValue: "invaliddata";
};

/** @internal */
export const BadRequestResponseImsxCodeMinorField$outboundSchema: z.ZodType<
  BadRequestResponseImsxCodeMinorField$Outbound,
  z.ZodTypeDef,
  BadRequestResponseImsxCodeMinorField
> = z.object({
  imsxCodeMinorFieldName: z.literal("TargetEndSystem").default(
    "TargetEndSystem" as const,
  ),
  imsxCodeMinorFieldValue: z.literal("invaliddata").default(
    "invaliddata" as const,
  ),
}).transform((v) => {
  return remap$(v, {
    imsxCodeMinorFieldName: "imsx_codeMinorFieldName",
    imsxCodeMinorFieldValue: "imsx_codeMinorFieldValue",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BadRequestResponseImsxCodeMinorField$ {
  /** @deprecated use `BadRequestResponseImsxCodeMinorField$inboundSchema` instead. */
  export const inboundSchema =
    BadRequestResponseImsxCodeMinorField$inboundSchema;
  /** @deprecated use `BadRequestResponseImsxCodeMinorField$outboundSchema` instead. */
  export const outboundSchema =
    BadRequestResponseImsxCodeMinorField$outboundSchema;
  /** @deprecated use `BadRequestResponseImsxCodeMinorField$Outbound` instead. */
  export type Outbound = BadRequestResponseImsxCodeMinorField$Outbound;
}

export function badRequestResponseImsxCodeMinorFieldToJSON(
  badRequestResponseImsxCodeMinorField: BadRequestResponseImsxCodeMinorField,
): string {
  return JSON.stringify(
    BadRequestResponseImsxCodeMinorField$outboundSchema.parse(
      badRequestResponseImsxCodeMinorField,
    ),
  );
}

export function badRequestResponseImsxCodeMinorFieldFromJSON(
  jsonString: string,
): SafeParseResult<BadRequestResponseImsxCodeMinorField, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      BadRequestResponseImsxCodeMinorField$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BadRequestResponseImsxCodeMinorField' from JSON`,
  );
}

/** @internal */
export const BadRequestResponseImsxCodeMinor$inboundSchema: z.ZodType<
  BadRequestResponseImsxCodeMinor,
  z.ZodTypeDef,
  unknown
> = z.object({
  imsx_codeMinorField: z.array(
    z.lazy(() => BadRequestResponseImsxCodeMinorField$inboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    "imsx_codeMinorField": "imsxCodeMinorField",
  });
});

/** @internal */
export type BadRequestResponseImsxCodeMinor$Outbound = {
  imsx_codeMinorField: Array<BadRequestResponseImsxCodeMinorField$Outbound>;
};

/** @internal */
export const BadRequestResponseImsxCodeMinor$outboundSchema: z.ZodType<
  BadRequestResponseImsxCodeMinor$Outbound,
  z.ZodTypeDef,
  BadRequestResponseImsxCodeMinor
> = z.object({
  imsxCodeMinorField: z.array(
    z.lazy(() => BadRequestResponseImsxCodeMinorField$outboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    imsxCodeMinorField: "imsx_codeMinorField",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BadRequestResponseImsxCodeMinor$ {
  /** @deprecated use `BadRequestResponseImsxCodeMinor$inboundSchema` instead. */
  export const inboundSchema = BadRequestResponseImsxCodeMinor$inboundSchema;
  /** @deprecated use `BadRequestResponseImsxCodeMinor$outboundSchema` instead. */
  export const outboundSchema = BadRequestResponseImsxCodeMinor$outboundSchema;
  /** @deprecated use `BadRequestResponseImsxCodeMinor$Outbound` instead. */
  export type Outbound = BadRequestResponseImsxCodeMinor$Outbound;
}

export function badRequestResponseImsxCodeMinorToJSON(
  badRequestResponseImsxCodeMinor: BadRequestResponseImsxCodeMinor,
): string {
  return JSON.stringify(
    BadRequestResponseImsxCodeMinor$outboundSchema.parse(
      badRequestResponseImsxCodeMinor,
    ),
  );
}

export function badRequestResponseImsxCodeMinorFromJSON(
  jsonString: string,
): SafeParseResult<BadRequestResponseImsxCodeMinor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BadRequestResponseImsxCodeMinor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BadRequestResponseImsxCodeMinor' from JSON`,
  );
}

/** @internal */
export const BadRequestResponseError$inboundSchema: z.ZodType<
  BadRequestResponseError,
  z.ZodTypeDef,
  unknown
> = z.object({
  imsx_codeMajor: z.literal("failure"),
  imsx_severity: z.literal("error"),
  imsx_description: z.string(),
  imsx_CodeMinor: z.lazy(() => BadRequestResponseImsxCodeMinor$inboundSchema),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "imsx_codeMajor": "imsxCodeMajor",
      "imsx_severity": "imsxSeverity",
      "imsx_description": "imsxDescription",
      "imsx_CodeMinor": "imsxCodeMinor",
    });

    return new BadRequestResponseError(remapped);
  });

/** @internal */
export type BadRequestResponseError$Outbound = {
  imsx_codeMajor: "failure";
  imsx_severity: "error";
  imsx_description: string;
  imsx_CodeMinor: BadRequestResponseImsxCodeMinor$Outbound;
};

/** @internal */
export const BadRequestResponseError$outboundSchema: z.ZodType<
  BadRequestResponseError$Outbound,
  z.ZodTypeDef,
  BadRequestResponseError
> = z.instanceof(BadRequestResponseError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      imsxCodeMajor: z.literal("failure").default("failure" as const),
      imsxSeverity: z.literal("error").default("error" as const),
      imsxDescription: z.string(),
      imsxCodeMinor: z.lazy(() =>
        BadRequestResponseImsxCodeMinor$outboundSchema
      ),
    }).transform((v) => {
      return remap$(v, {
        imsxCodeMajor: "imsx_codeMajor",
        imsxSeverity: "imsx_severity",
        imsxDescription: "imsx_description",
        imsxCodeMinor: "imsx_CodeMinor",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BadRequestResponseError$ {
  /** @deprecated use `BadRequestResponseError$inboundSchema` instead. */
  export const inboundSchema = BadRequestResponseError$inboundSchema;
  /** @deprecated use `BadRequestResponseError$outboundSchema` instead. */
  export const outboundSchema = BadRequestResponseError$outboundSchema;
  /** @deprecated use `BadRequestResponseError$Outbound` instead. */
  export type Outbound = BadRequestResponseError$Outbound;
}
