/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { PowerPathError } from "./powerpatherror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type NotFoundResponseImsxCodeMinorField = {
  imsxCodeMinorFieldName: "TargetEndSystem";
  imsxCodeMinorFieldValue: "unknownobject";
};

export type NotFoundResponseImsxCodeMinor = {
  imsxCodeMinorField: Array<NotFoundResponseImsxCodeMinorField>;
};

export type NotFoundResponseErrorData = {
  imsxCodeMajor: "failure";
  imsxSeverity: "error";
  imsxDescription: string;
  imsxCodeMinor: NotFoundResponseImsxCodeMinor;
  imsxErrorDetails?: Array<{ [k: string]: string }> | undefined;
};

export class NotFoundResponseError extends PowerPathError {
  imsxCodeMajor: "failure";
  imsxSeverity: "error";
  imsxDescription: string;
  imsxCodeMinor: NotFoundResponseImsxCodeMinor;
  imsxErrorDetails?: Array<{ [k: string]: string }> | undefined;

  /** The original data that was passed to this error instance. */
  data$: NotFoundResponseErrorData;

  constructor(
    err: NotFoundResponseErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.imsxCodeMajor = err.imsxCodeMajor;
    this.imsxSeverity = err.imsxSeverity;
    this.imsxDescription = err.imsxDescription;
    this.imsxCodeMinor = err.imsxCodeMinor;
    if (err.imsxErrorDetails != null) {
      this.imsxErrorDetails = err.imsxErrorDetails;
    }

    this.name = "NotFoundResponseError";
  }
}

/** @internal */
export const NotFoundResponseImsxCodeMinorField$inboundSchema: z.ZodType<
  NotFoundResponseImsxCodeMinorField,
  z.ZodTypeDef,
  unknown
> = z.object({
  imsx_codeMinorFieldName: z.literal("TargetEndSystem"),
  imsx_codeMinorFieldValue: z.literal("unknownobject"),
}).transform((v) => {
  return remap$(v, {
    "imsx_codeMinorFieldName": "imsxCodeMinorFieldName",
    "imsx_codeMinorFieldValue": "imsxCodeMinorFieldValue",
  });
});
/** @internal */
export type NotFoundResponseImsxCodeMinorField$Outbound = {
  imsx_codeMinorFieldName: "TargetEndSystem";
  imsx_codeMinorFieldValue: "unknownobject";
};

/** @internal */
export const NotFoundResponseImsxCodeMinorField$outboundSchema: z.ZodType<
  NotFoundResponseImsxCodeMinorField$Outbound,
  z.ZodTypeDef,
  NotFoundResponseImsxCodeMinorField
> = z.object({
  imsxCodeMinorFieldName: z.literal("TargetEndSystem"),
  imsxCodeMinorFieldValue: z.literal("unknownobject"),
}).transform((v) => {
  return remap$(v, {
    imsxCodeMinorFieldName: "imsx_codeMinorFieldName",
    imsxCodeMinorFieldValue: "imsx_codeMinorFieldValue",
  });
});

export function notFoundResponseImsxCodeMinorFieldToJSON(
  notFoundResponseImsxCodeMinorField: NotFoundResponseImsxCodeMinorField,
): string {
  return JSON.stringify(
    NotFoundResponseImsxCodeMinorField$outboundSchema.parse(
      notFoundResponseImsxCodeMinorField,
    ),
  );
}
export function notFoundResponseImsxCodeMinorFieldFromJSON(
  jsonString: string,
): SafeParseResult<NotFoundResponseImsxCodeMinorField, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      NotFoundResponseImsxCodeMinorField$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NotFoundResponseImsxCodeMinorField' from JSON`,
  );
}

/** @internal */
export const NotFoundResponseImsxCodeMinor$inboundSchema: z.ZodType<
  NotFoundResponseImsxCodeMinor,
  z.ZodTypeDef,
  unknown
> = z.object({
  imsx_codeMinorField: z.array(
    z.lazy(() => NotFoundResponseImsxCodeMinorField$inboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    "imsx_codeMinorField": "imsxCodeMinorField",
  });
});
/** @internal */
export type NotFoundResponseImsxCodeMinor$Outbound = {
  imsx_codeMinorField: Array<NotFoundResponseImsxCodeMinorField$Outbound>;
};

/** @internal */
export const NotFoundResponseImsxCodeMinor$outboundSchema: z.ZodType<
  NotFoundResponseImsxCodeMinor$Outbound,
  z.ZodTypeDef,
  NotFoundResponseImsxCodeMinor
> = z.object({
  imsxCodeMinorField: z.array(
    z.lazy(() => NotFoundResponseImsxCodeMinorField$outboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    imsxCodeMinorField: "imsx_codeMinorField",
  });
});

export function notFoundResponseImsxCodeMinorToJSON(
  notFoundResponseImsxCodeMinor: NotFoundResponseImsxCodeMinor,
): string {
  return JSON.stringify(
    NotFoundResponseImsxCodeMinor$outboundSchema.parse(
      notFoundResponseImsxCodeMinor,
    ),
  );
}
export function notFoundResponseImsxCodeMinorFromJSON(
  jsonString: string,
): SafeParseResult<NotFoundResponseImsxCodeMinor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NotFoundResponseImsxCodeMinor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NotFoundResponseImsxCodeMinor' from JSON`,
  );
}

/** @internal */
export const NotFoundResponseError$inboundSchema: z.ZodType<
  NotFoundResponseError,
  z.ZodTypeDef,
  unknown
> = z.object({
  imsx_codeMajor: z.literal("failure"),
  imsx_severity: z.literal("error"),
  imsx_description: z.string(),
  imsx_CodeMinor: z.lazy(() => NotFoundResponseImsxCodeMinor$inboundSchema),
  imsx_error_details: z.array(z.record(z.string())).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "imsx_codeMajor": "imsxCodeMajor",
      "imsx_severity": "imsxSeverity",
      "imsx_description": "imsxDescription",
      "imsx_CodeMinor": "imsxCodeMinor",
      "imsx_error_details": "imsxErrorDetails",
    });

    return new NotFoundResponseError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type NotFoundResponseError$Outbound = {
  imsx_codeMajor: "failure";
  imsx_severity: "error";
  imsx_description: string;
  imsx_CodeMinor: NotFoundResponseImsxCodeMinor$Outbound;
  imsx_error_details?: Array<{ [k: string]: string }> | undefined;
};

/** @internal */
export const NotFoundResponseError$outboundSchema: z.ZodType<
  NotFoundResponseError$Outbound,
  z.ZodTypeDef,
  NotFoundResponseError
> = z.instanceof(NotFoundResponseError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      imsxCodeMajor: z.literal("failure"),
      imsxSeverity: z.literal("error"),
      imsxDescription: z.string(),
      imsxCodeMinor: z.lazy(() => NotFoundResponseImsxCodeMinor$outboundSchema),
      imsxErrorDetails: z.array(z.record(z.string())).optional(),
    }).transform((v) => {
      return remap$(v, {
        imsxCodeMajor: "imsx_codeMajor",
        imsxSeverity: "imsx_severity",
        imsxDescription: "imsx_description",
        imsxCodeMinor: "imsx_CodeMinor",
        imsxErrorDetails: "imsx_error_details",
      });
    }),
  );
