/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { PowerPathError } from "./powerpatherror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type UnauthorizedRequestResponseImsxCodeMinorField = {
  imsxCodeMinorFieldName?: "TargetEndSystem" | undefined;
  imsxCodeMinorFieldValue?: "unauthorisedrequest" | undefined;
};

export type UnauthorizedRequestResponseImsxCodeMinor = {
  imsxCodeMinorField: Array<UnauthorizedRequestResponseImsxCodeMinorField>;
};

export type UnauthorizedRequestResponseErrorData = {
  imsxCodeMajor: "failure";
  imsxSeverity: "error";
  imsxDescription: string;
  imsxCodeMinor: UnauthorizedRequestResponseImsxCodeMinor;
  imsxErrorDetails?: Array<{ [k: string]: string }> | undefined;
};

export class UnauthorizedRequestResponseError extends PowerPathError {
  imsxCodeMajor: "failure";
  imsxSeverity: "error";
  imsxDescription: string;
  imsxCodeMinor: UnauthorizedRequestResponseImsxCodeMinor;
  imsxErrorDetails?: Array<{ [k: string]: string }> | undefined;

  /** The original data that was passed to this error instance. */
  data$: UnauthorizedRequestResponseErrorData;

  constructor(
    err: UnauthorizedRequestResponseErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.imsxCodeMajor = err.imsxCodeMajor;
    this.imsxSeverity = err.imsxSeverity;
    this.imsxDescription = err.imsxDescription;
    this.imsxCodeMinor = err.imsxCodeMinor;
    if (err.imsxErrorDetails != null) {
      this.imsxErrorDetails = err.imsxErrorDetails;
    }

    this.name = "UnauthorizedRequestResponseError";
  }
}

/** @internal */
export const UnauthorizedRequestResponseImsxCodeMinorField$inboundSchema:
  z.ZodType<
    UnauthorizedRequestResponseImsxCodeMinorField,
    z.ZodTypeDef,
    unknown
  > = z.object({
    imsx_codeMinorFieldName: z.literal("TargetEndSystem").default(
      "TargetEndSystem",
    ).optional(),
    imsx_codeMinorFieldValue: z.literal("unauthorisedrequest").default(
      "unauthorisedrequest",
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "imsx_codeMinorFieldName": "imsxCodeMinorFieldName",
      "imsx_codeMinorFieldValue": "imsxCodeMinorFieldValue",
    });
  });

/** @internal */
export type UnauthorizedRequestResponseImsxCodeMinorField$Outbound = {
  imsx_codeMinorFieldName: "TargetEndSystem";
  imsx_codeMinorFieldValue: "unauthorisedrequest";
};

/** @internal */
export const UnauthorizedRequestResponseImsxCodeMinorField$outboundSchema:
  z.ZodType<
    UnauthorizedRequestResponseImsxCodeMinorField$Outbound,
    z.ZodTypeDef,
    UnauthorizedRequestResponseImsxCodeMinorField
  > = z.object({
    imsxCodeMinorFieldName: z.literal("TargetEndSystem").default(
      "TargetEndSystem" as const,
    ),
    imsxCodeMinorFieldValue: z.literal("unauthorisedrequest").default(
      "unauthorisedrequest" as const,
    ),
  }).transform((v) => {
    return remap$(v, {
      imsxCodeMinorFieldName: "imsx_codeMinorFieldName",
      imsxCodeMinorFieldValue: "imsx_codeMinorFieldValue",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnauthorizedRequestResponseImsxCodeMinorField$ {
  /** @deprecated use `UnauthorizedRequestResponseImsxCodeMinorField$inboundSchema` instead. */
  export const inboundSchema =
    UnauthorizedRequestResponseImsxCodeMinorField$inboundSchema;
  /** @deprecated use `UnauthorizedRequestResponseImsxCodeMinorField$outboundSchema` instead. */
  export const outboundSchema =
    UnauthorizedRequestResponseImsxCodeMinorField$outboundSchema;
  /** @deprecated use `UnauthorizedRequestResponseImsxCodeMinorField$Outbound` instead. */
  export type Outbound = UnauthorizedRequestResponseImsxCodeMinorField$Outbound;
}

export function unauthorizedRequestResponseImsxCodeMinorFieldToJSON(
  unauthorizedRequestResponseImsxCodeMinorField:
    UnauthorizedRequestResponseImsxCodeMinorField,
): string {
  return JSON.stringify(
    UnauthorizedRequestResponseImsxCodeMinorField$outboundSchema.parse(
      unauthorizedRequestResponseImsxCodeMinorField,
    ),
  );
}

export function unauthorizedRequestResponseImsxCodeMinorFieldFromJSON(
  jsonString: string,
): SafeParseResult<
  UnauthorizedRequestResponseImsxCodeMinorField,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UnauthorizedRequestResponseImsxCodeMinorField$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UnauthorizedRequestResponseImsxCodeMinorField' from JSON`,
  );
}

/** @internal */
export const UnauthorizedRequestResponseImsxCodeMinor$inboundSchema: z.ZodType<
  UnauthorizedRequestResponseImsxCodeMinor,
  z.ZodTypeDef,
  unknown
> = z.object({
  imsx_codeMinorField: z.array(
    z.lazy(() => UnauthorizedRequestResponseImsxCodeMinorField$inboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    "imsx_codeMinorField": "imsxCodeMinorField",
  });
});

/** @internal */
export type UnauthorizedRequestResponseImsxCodeMinor$Outbound = {
  imsx_codeMinorField: Array<
    UnauthorizedRequestResponseImsxCodeMinorField$Outbound
  >;
};

/** @internal */
export const UnauthorizedRequestResponseImsxCodeMinor$outboundSchema: z.ZodType<
  UnauthorizedRequestResponseImsxCodeMinor$Outbound,
  z.ZodTypeDef,
  UnauthorizedRequestResponseImsxCodeMinor
> = z.object({
  imsxCodeMinorField: z.array(
    z.lazy(() => UnauthorizedRequestResponseImsxCodeMinorField$outboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    imsxCodeMinorField: "imsx_codeMinorField",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnauthorizedRequestResponseImsxCodeMinor$ {
  /** @deprecated use `UnauthorizedRequestResponseImsxCodeMinor$inboundSchema` instead. */
  export const inboundSchema =
    UnauthorizedRequestResponseImsxCodeMinor$inboundSchema;
  /** @deprecated use `UnauthorizedRequestResponseImsxCodeMinor$outboundSchema` instead. */
  export const outboundSchema =
    UnauthorizedRequestResponseImsxCodeMinor$outboundSchema;
  /** @deprecated use `UnauthorizedRequestResponseImsxCodeMinor$Outbound` instead. */
  export type Outbound = UnauthorizedRequestResponseImsxCodeMinor$Outbound;
}

export function unauthorizedRequestResponseImsxCodeMinorToJSON(
  unauthorizedRequestResponseImsxCodeMinor:
    UnauthorizedRequestResponseImsxCodeMinor,
): string {
  return JSON.stringify(
    UnauthorizedRequestResponseImsxCodeMinor$outboundSchema.parse(
      unauthorizedRequestResponseImsxCodeMinor,
    ),
  );
}

export function unauthorizedRequestResponseImsxCodeMinorFromJSON(
  jsonString: string,
): SafeParseResult<
  UnauthorizedRequestResponseImsxCodeMinor,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UnauthorizedRequestResponseImsxCodeMinor$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UnauthorizedRequestResponseImsxCodeMinor' from JSON`,
  );
}

/** @internal */
export const UnauthorizedRequestResponseError$inboundSchema: z.ZodType<
  UnauthorizedRequestResponseError,
  z.ZodTypeDef,
  unknown
> = z.object({
  imsx_codeMajor: z.literal("failure").default("failure"),
  imsx_severity: z.literal("error").default("error"),
  imsx_description: z.string(),
  imsx_CodeMinor: z.lazy(() =>
    UnauthorizedRequestResponseImsxCodeMinor$inboundSchema
  ),
  imsx_error_details: z.array(z.record(z.string())).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "imsx_codeMajor": "imsxCodeMajor",
      "imsx_severity": "imsxSeverity",
      "imsx_description": "imsxDescription",
      "imsx_CodeMinor": "imsxCodeMinor",
      "imsx_error_details": "imsxErrorDetails",
    });

    return new UnauthorizedRequestResponseError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type UnauthorizedRequestResponseError$Outbound = {
  imsx_codeMajor: "failure";
  imsx_severity: "error";
  imsx_description: string;
  imsx_CodeMinor: UnauthorizedRequestResponseImsxCodeMinor$Outbound;
  imsx_error_details?: Array<{ [k: string]: string }> | undefined;
};

/** @internal */
export const UnauthorizedRequestResponseError$outboundSchema: z.ZodType<
  UnauthorizedRequestResponseError$Outbound,
  z.ZodTypeDef,
  UnauthorizedRequestResponseError
> = z.instanceof(UnauthorizedRequestResponseError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      imsxCodeMajor: z.literal("failure").default("failure" as const),
      imsxSeverity: z.literal("error").default("error" as const),
      imsxDescription: z.string(),
      imsxCodeMinor: z.lazy(() =>
        UnauthorizedRequestResponseImsxCodeMinor$outboundSchema
      ),
      imsxErrorDetails: z.array(z.record(z.string())).optional(),
    }).transform((v) => {
      return remap$(v, {
        imsxCodeMajor: "imsx_codeMajor",
        imsxSeverity: "imsx_severity",
        imsxDescription: "imsx_description",
        imsxCodeMinor: "imsx_CodeMinor",
        imsxErrorDetails: "imsx_error_details",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnauthorizedRequestResponseError$ {
  /** @deprecated use `UnauthorizedRequestResponseError$inboundSchema` instead. */
  export const inboundSchema = UnauthorizedRequestResponseError$inboundSchema;
  /** @deprecated use `UnauthorizedRequestResponseError$outboundSchema` instead. */
  export const outboundSchema = UnauthorizedRequestResponseError$outboundSchema;
  /** @deprecated use `UnauthorizedRequestResponseError$Outbound` instead. */
  export type Outbound = UnauthorizedRequestResponseError$Outbound;
}
