/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { lessonsCreateAttempt } from "../../funcs/lessonsCreateAttempt.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateNewAttemptRequest$inboundSchema.optional(),
};

export const tool$lessonsCreateAttempt: ToolDefinition<typeof args> = {
  name: "lessons-create-attempt",
  description: `Create new attempt

Creates a new attempt for a student in a lesson if current attempt is completed`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await lessonsCreateAttempt(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
