/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { powerPathLessonPlansDeleteLessonPlan } from "../../funcs/powerPathLessonPlansDeleteLessonPlan.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteLessonPlanRequest$inboundSchema,
};

export const tool$powerPathLessonPlansDeleteLessonPlan: ToolDefinition<
  typeof args
> = {
  name: "power-path-lesson-plans-delete-lesson-plan",
  description: `Delete a lesson plan


    Deletes a lesson plan by its ID.
    This will delete the lesson plan and all of its associated lesson plan items.
    `,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await powerPathLessonPlansDeleteLessonPlan(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
