/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { powerPathPlacementGetAllPlacementTests } from "../../funcs/powerPathPlacementGetAllPlacementTests.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAllPlacementTestsRequest$inboundSchema,
};

export const tool$powerPathPlacementGetAllPlacementTests: ToolDefinition<
  typeof args
> = {
  name: "power-path-placement-get-all-placement-tests",
  description: `Get all placement tests

Returns all placement tests for a subject, including available results for each.

A 'Lesson' (placement test) in this context is a ComponentResource object which has a Resource object with metadata.lessonType = "placement" associated with it.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await powerPathPlacementGetAllPlacementTests(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
