/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { powerPathPlacementGetSubjectProgress } from "../../funcs/powerPathPlacementGetSubjectProgress.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetSubjectProgressRequest$inboundSchema,
};

export const tool$powerPathPlacementGetSubjectProgress: ToolDefinition<
  typeof args
> = {
  name: "power-path-placement-get-subject-progress",
  description: `Get subject progress

Returns the progress the student has made in the given subject
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await powerPathPlacementGetSubjectProgress(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
