/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateExternalTestOutRequest =
  | components.CreateExternalTestOutInput
  | components.CreateExternalPlacementInput;

export const CreateExternalTestOutLessonType = {
  Powerpath100: "powerpath-100",
  Quiz: "quiz",
  TestOut: "test-out",
  Placement: "placement",
} as const;
export type CreateExternalTestOutLessonType = ClosedEnum<
  typeof CreateExternalTestOutLessonType
>;

/**
 * Success
 */
export type CreateExternalTestOutResponse = {
  lessonType: CreateExternalTestOutLessonType;
  /**
   * The sourcedId of the created external test reference (ComponentResource)
   */
  lessonId: string;
  /**
   * The sourcedId of the component (unit) containing the test
   */
  courseComponentId: string;
  /**
   * The sourcedId of the resource representing the external test
   */
  resourceId: string;
  /**
   * The URL to the external test system
   */
  launchUrl?: string | undefined;
  /**
   * The tool provider id
   */
  toolProvider: string;
  /**
   * The ID of the test in the spreadsheet
   */
  vendorId: string;
  /**
   * The courseId to enroll the student in if they fail the placement test (optional)
   */
  courseIdOnFail?: string | null | undefined;
  /**
   * The grades for the resource
   */
  grades?: Array<number> | undefined;
};

/** @internal */
export const CreateExternalTestOutRequest$inboundSchema: z.ZodType<
  CreateExternalTestOutRequest,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.CreateExternalTestOutInput$inboundSchema,
  components.CreateExternalPlacementInput$inboundSchema,
]);
/** @internal */
export type CreateExternalTestOutRequest$Outbound =
  | components.CreateExternalTestOutInput$Outbound
  | components.CreateExternalPlacementInput$Outbound;

/** @internal */
export const CreateExternalTestOutRequest$outboundSchema: z.ZodType<
  CreateExternalTestOutRequest$Outbound,
  z.ZodTypeDef,
  CreateExternalTestOutRequest
> = z.union([
  components.CreateExternalTestOutInput$outboundSchema,
  components.CreateExternalPlacementInput$outboundSchema,
]);

export function createExternalTestOutRequestToJSON(
  createExternalTestOutRequest: CreateExternalTestOutRequest,
): string {
  return JSON.stringify(
    CreateExternalTestOutRequest$outboundSchema.parse(
      createExternalTestOutRequest,
    ),
  );
}
export function createExternalTestOutRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateExternalTestOutRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateExternalTestOutRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateExternalTestOutRequest' from JSON`,
  );
}

/** @internal */
export const CreateExternalTestOutLessonType$inboundSchema: z.ZodNativeEnum<
  typeof CreateExternalTestOutLessonType
> = z.nativeEnum(CreateExternalTestOutLessonType);
/** @internal */
export const CreateExternalTestOutLessonType$outboundSchema: z.ZodNativeEnum<
  typeof CreateExternalTestOutLessonType
> = CreateExternalTestOutLessonType$inboundSchema;

/** @internal */
export const CreateExternalTestOutResponse$inboundSchema: z.ZodType<
  CreateExternalTestOutResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  lessonType: CreateExternalTestOutLessonType$inboundSchema,
  lessonId: z.string(),
  courseComponentId: z.string(),
  resourceId: z.string(),
  launchUrl: z.string().optional(),
  toolProvider: z.string(),
  vendorId: z.string(),
  courseIdOnFail: z.nullable(z.string()).optional(),
  grades: z.array(z.number()).optional(),
});
/** @internal */
export type CreateExternalTestOutResponse$Outbound = {
  lessonType: string;
  lessonId: string;
  courseComponentId: string;
  resourceId: string;
  launchUrl?: string | undefined;
  toolProvider: string;
  vendorId: string;
  courseIdOnFail?: string | null | undefined;
  grades?: Array<number> | undefined;
};

/** @internal */
export const CreateExternalTestOutResponse$outboundSchema: z.ZodType<
  CreateExternalTestOutResponse$Outbound,
  z.ZodTypeDef,
  CreateExternalTestOutResponse
> = z.object({
  lessonType: CreateExternalTestOutLessonType$outboundSchema,
  lessonId: z.string(),
  courseComponentId: z.string(),
  resourceId: z.string(),
  launchUrl: z.string().optional(),
  toolProvider: z.string(),
  vendorId: z.string(),
  courseIdOnFail: z.nullable(z.string()).optional(),
  grades: z.array(z.number()).optional(),
});

export function createExternalTestOutResponseToJSON(
  createExternalTestOutResponse: CreateExternalTestOutResponse,
): string {
  return JSON.stringify(
    CreateExternalTestOutResponse$outboundSchema.parse(
      createExternalTestOutResponse,
    ),
  );
}
export function createExternalTestOutResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateExternalTestOutResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateExternalTestOutResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateExternalTestOutResponse' from JSON`,
  );
}
