/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteLessonPlanRequest = {
  /**
   * Lesson plan ID
   */
  lessonPlanId: string;
};

/** @internal */
export const DeleteLessonPlanRequest$inboundSchema: z.ZodType<
  DeleteLessonPlanRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  lessonPlanId: z.string(),
});

/** @internal */
export type DeleteLessonPlanRequest$Outbound = {
  lessonPlanId: string;
};

/** @internal */
export const DeleteLessonPlanRequest$outboundSchema: z.ZodType<
  DeleteLessonPlanRequest$Outbound,
  z.ZodTypeDef,
  DeleteLessonPlanRequest
> = z.object({
  lessonPlanId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteLessonPlanRequest$ {
  /** @deprecated use `DeleteLessonPlanRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteLessonPlanRequest$inboundSchema;
  /** @deprecated use `DeleteLessonPlanRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteLessonPlanRequest$outboundSchema;
  /** @deprecated use `DeleteLessonPlanRequest$Outbound` instead. */
  export type Outbound = DeleteLessonPlanRequest$Outbound;
}

export function deleteLessonPlanRequestToJSON(
  deleteLessonPlanRequest: DeleteLessonPlanRequest,
): string {
  return JSON.stringify(
    DeleteLessonPlanRequest$outboundSchema.parse(deleteLessonPlanRequest),
  );
}

export function deleteLessonPlanRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteLessonPlanRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteLessonPlanRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteLessonPlanRequest' from JSON`,
  );
}
