/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteLessonPlanItemRequest = {
  /**
   * Lesson plan item ID
   */
  lessonPlanItemId: string;
};

/** @internal */
export const DeleteLessonPlanItemRequest$inboundSchema: z.ZodType<
  DeleteLessonPlanItemRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  lessonPlanItemId: z.string(),
});

/** @internal */
export type DeleteLessonPlanItemRequest$Outbound = {
  lessonPlanItemId: string;
};

/** @internal */
export const DeleteLessonPlanItemRequest$outboundSchema: z.ZodType<
  DeleteLessonPlanItemRequest$Outbound,
  z.ZodTypeDef,
  DeleteLessonPlanItemRequest
> = z.object({
  lessonPlanItemId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteLessonPlanItemRequest$ {
  /** @deprecated use `DeleteLessonPlanItemRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteLessonPlanItemRequest$inboundSchema;
  /** @deprecated use `DeleteLessonPlanItemRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteLessonPlanItemRequest$outboundSchema;
  /** @deprecated use `DeleteLessonPlanItemRequest$Outbound` instead. */
  export type Outbound = DeleteLessonPlanItemRequest$Outbound;
}

export function deleteLessonPlanItemRequestToJSON(
  deleteLessonPlanItemRequest: DeleteLessonPlanItemRequest,
): string {
  return JSON.stringify(
    DeleteLessonPlanItemRequest$outboundSchema.parse(
      deleteLessonPlanItemRequest,
    ),
  );
}

export function deleteLessonPlanItemRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteLessonPlanItemRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteLessonPlanItemRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteLessonPlanItemRequest' from JSON`,
  );
}
