/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteLessonPlanRequest = {
  /**
   * Lesson plan ID
   */
  lessonPlanId: string;
};

/** @internal */
export const DeleteLessonPlanRequest$inboundSchema: z.ZodType<
  DeleteLessonPlanRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  lessonPlanId: z.string(),
});
/** @internal */
export type DeleteLessonPlanRequest$Outbound = {
  lessonPlanId: string;
};

/** @internal */
export const DeleteLessonPlanRequest$outboundSchema: z.ZodType<
  DeleteLessonPlanRequest$Outbound,
  z.ZodTypeDef,
  DeleteLessonPlanRequest
> = z.object({
  lessonPlanId: z.string(),
});

export function deleteLessonPlanRequestToJSON(
  deleteLessonPlanRequest: DeleteLessonPlanRequest,
): string {
  return JSON.stringify(
    DeleteLessonPlanRequest$outboundSchema.parse(deleteLessonPlanRequest),
  );
}
export function deleteLessonPlanRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteLessonPlanRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteLessonPlanRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteLessonPlanRequest' from JSON`,
  );
}
