/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FinalStudentAssessmentResponseRequest = {
  /**
   * The sourcedId of the student
   */
  student: string;
  /**
   * The sourcedId of the lesson (ComponentResource)
   */
  lesson: string;
};

export const FinalStudentAssessmentResponseLessonType = {
  Quiz: "quiz",
  TestOut: "test-out",
  Placement: "placement",
} as const;
export type FinalStudentAssessmentResponseLessonType = ClosedEnum<
  typeof FinalStudentAssessmentResponseLessonType
>;

/**
 * Success
 */
export type FinalStudentAssessmentResponseResponse = {
  lessonType: FinalStudentAssessmentResponseLessonType;
  /**
   * Whether the lesson has been finalized in the current attempt
   */
  finalized: boolean;
  /**
   * The attempt number
   */
  attempt: number;
};

/** @internal */
export const FinalStudentAssessmentResponseRequest$inboundSchema: z.ZodType<
  FinalStudentAssessmentResponseRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  student: z.string(),
  lesson: z.string(),
});
/** @internal */
export type FinalStudentAssessmentResponseRequest$Outbound = {
  student: string;
  lesson: string;
};

/** @internal */
export const FinalStudentAssessmentResponseRequest$outboundSchema: z.ZodType<
  FinalStudentAssessmentResponseRequest$Outbound,
  z.ZodTypeDef,
  FinalStudentAssessmentResponseRequest
> = z.object({
  student: z.string(),
  lesson: z.string(),
});

export function finalStudentAssessmentResponseRequestToJSON(
  finalStudentAssessmentResponseRequest: FinalStudentAssessmentResponseRequest,
): string {
  return JSON.stringify(
    FinalStudentAssessmentResponseRequest$outboundSchema.parse(
      finalStudentAssessmentResponseRequest,
    ),
  );
}
export function finalStudentAssessmentResponseRequestFromJSON(
  jsonString: string,
): SafeParseResult<FinalStudentAssessmentResponseRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FinalStudentAssessmentResponseRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FinalStudentAssessmentResponseRequest' from JSON`,
  );
}

/** @internal */
export const FinalStudentAssessmentResponseLessonType$inboundSchema:
  z.ZodNativeEnum<typeof FinalStudentAssessmentResponseLessonType> = z
    .nativeEnum(FinalStudentAssessmentResponseLessonType);
/** @internal */
export const FinalStudentAssessmentResponseLessonType$outboundSchema:
  z.ZodNativeEnum<typeof FinalStudentAssessmentResponseLessonType> =
    FinalStudentAssessmentResponseLessonType$inboundSchema;

/** @internal */
export const FinalStudentAssessmentResponseResponse$inboundSchema: z.ZodType<
  FinalStudentAssessmentResponseResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  lessonType: FinalStudentAssessmentResponseLessonType$inboundSchema,
  finalized: z.boolean(),
  attempt: z.number(),
});
/** @internal */
export type FinalStudentAssessmentResponseResponse$Outbound = {
  lessonType: string;
  finalized: boolean;
  attempt: number;
};

/** @internal */
export const FinalStudentAssessmentResponseResponse$outboundSchema: z.ZodType<
  FinalStudentAssessmentResponseResponse$Outbound,
  z.ZodTypeDef,
  FinalStudentAssessmentResponseResponse
> = z.object({
  lessonType: FinalStudentAssessmentResponseLessonType$outboundSchema,
  finalized: z.boolean(),
  attempt: z.number(),
});

export function finalStudentAssessmentResponseResponseToJSON(
  finalStudentAssessmentResponseResponse:
    FinalStudentAssessmentResponseResponse,
): string {
  return JSON.stringify(
    FinalStudentAssessmentResponseResponse$outboundSchema.parse(
      finalStudentAssessmentResponseResponse,
    ),
  );
}
export function finalStudentAssessmentResponseResponseFromJSON(
  jsonString: string,
): SafeParseResult<FinalStudentAssessmentResponseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FinalStudentAssessmentResponseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FinalStudentAssessmentResponseResponse' from JSON`,
  );
}
