/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCourseSyllabusRequest = {
  /**
   * The course sourcedId
   */
  courseSourcedId: string;
};

/**
 * Success
 */
export type GetCourseSyllabusResponse = {
  /**
   * The course syllabus content
   */
  syllabus?: any | undefined;
};

/** @internal */
export const GetCourseSyllabusRequest$inboundSchema: z.ZodType<
  GetCourseSyllabusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  courseSourcedId: z.string(),
});
/** @internal */
export type GetCourseSyllabusRequest$Outbound = {
  courseSourcedId: string;
};

/** @internal */
export const GetCourseSyllabusRequest$outboundSchema: z.ZodType<
  GetCourseSyllabusRequest$Outbound,
  z.ZodTypeDef,
  GetCourseSyllabusRequest
> = z.object({
  courseSourcedId: z.string(),
});

export function getCourseSyllabusRequestToJSON(
  getCourseSyllabusRequest: GetCourseSyllabusRequest,
): string {
  return JSON.stringify(
    GetCourseSyllabusRequest$outboundSchema.parse(getCourseSyllabusRequest),
  );
}
export function getCourseSyllabusRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCourseSyllabusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCourseSyllabusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCourseSyllabusRequest' from JSON`,
  );
}

/** @internal */
export const GetCourseSyllabusResponse$inboundSchema: z.ZodType<
  GetCourseSyllabusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  syllabus: z.any().optional(),
});
/** @internal */
export type GetCourseSyllabusResponse$Outbound = {
  syllabus?: any | undefined;
};

/** @internal */
export const GetCourseSyllabusResponse$outboundSchema: z.ZodType<
  GetCourseSyllabusResponse$Outbound,
  z.ZodTypeDef,
  GetCourseSyllabusResponse
> = z.object({
  syllabus: z.any().optional(),
});

export function getCourseSyllabusResponseToJSON(
  getCourseSyllabusResponse: GetCourseSyllabusResponse,
): string {
  return JSON.stringify(
    GetCourseSyllabusResponse$outboundSchema.parse(getCourseSyllabusResponse),
  );
}
export function getCourseSyllabusResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCourseSyllabusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCourseSyllabusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCourseSyllabusResponse' from JSON`,
  );
}
