/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export * from "./attachcomponent.js";
export * from "./attachresource.js";
export * from "./createexternalplacementtest.js";
export * from "./createexternaltestout.js";
export * from "./createlessonplan.js";
export * from "./createnewattempt.js";
export * from "./deletelessonplan.js";
export * from "./deletelessonplanitem.js";
export * from "./finalstudentassessmentresponse.js";
export * from "./getallplacementtests.js";
export * from "./getassessmentprogress.js";
export * from "./getattempts.js";
export * from "./getcourseprogress.js";
export * from "./getcoursesyllabus.js";
export * from "./getcurrentlevel.js";
export * from "./getnextplacementtest.js";
export * from "./getnextquestion.js";
export * from "./getsubjectprogress.js";
export * from "./gettree.js";
export * from "./importexternaltestassignmentresults.js";
export * from "./makeexternaltestassignment.js";
export * from "./resetattempt.js";
export * from "./testout.js";
export * from "./updatelessonplanitem.js";
export * from "./updatestudentitemresponse.js";
export * from "./updatestudentquestionresponse.js";
