/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LearningObjectiveSet = {
  source: string;
  learningObjectiveIds: Array<string>;
};

/** @internal */
export const LearningObjectiveSet$inboundSchema: z.ZodType<
  LearningObjectiveSet,
  z.ZodTypeDef,
  unknown
> = z.object({
  source: z.string(),
  learningObjectiveIds: z.array(z.string()),
});
/** @internal */
export type LearningObjectiveSet$Outbound = {
  source: string;
  learningObjectiveIds: Array<string>;
};

/** @internal */
export const LearningObjectiveSet$outboundSchema: z.ZodType<
  LearningObjectiveSet$Outbound,
  z.ZodTypeDef,
  LearningObjectiveSet
> = z.object({
  source: z.string(),
  learningObjectiveIds: z.array(z.string()),
});

export function learningObjectiveSetToJSON(
  learningObjectiveSet: LearningObjectiveSet,
): string {
  return JSON.stringify(
    LearningObjectiveSet$outboundSchema.parse(learningObjectiveSet),
  );
}
export function learningObjectiveSetFromJSON(
  jsonString: string,
): SafeParseResult<LearningObjectiveSet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LearningObjectiveSet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LearningObjectiveSet' from JSON`,
  );
}
