/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LearningObjectiveSetLearningObjectiveId = {
  learningObjectiveId: string;
  score?: number | undefined;
  textScore?: string | undefined;
};

export type LearningObjectiveSet = {
  source: string;
  learningObjectiveIds: Array<LearningObjectiveSetLearningObjectiveId>;
};

/** @internal */
export const LearningObjectiveSetLearningObjectiveId$inboundSchema: z.ZodType<
  LearningObjectiveSetLearningObjectiveId,
  z.ZodTypeDef,
  unknown
> = z.object({
  learningObjectiveId: z.string(),
  score: z.number().optional(),
  textScore: z.string().optional(),
});

/** @internal */
export type LearningObjectiveSetLearningObjectiveId$Outbound = {
  learningObjectiveId: string;
  score?: number | undefined;
  textScore?: string | undefined;
};

/** @internal */
export const LearningObjectiveSetLearningObjectiveId$outboundSchema: z.ZodType<
  LearningObjectiveSetLearningObjectiveId$Outbound,
  z.ZodTypeDef,
  LearningObjectiveSetLearningObjectiveId
> = z.object({
  learningObjectiveId: z.string(),
  score: z.number().optional(),
  textScore: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LearningObjectiveSetLearningObjectiveId$ {
  /** @deprecated use `LearningObjectiveSetLearningObjectiveId$inboundSchema` instead. */
  export const inboundSchema =
    LearningObjectiveSetLearningObjectiveId$inboundSchema;
  /** @deprecated use `LearningObjectiveSetLearningObjectiveId$outboundSchema` instead. */
  export const outboundSchema =
    LearningObjectiveSetLearningObjectiveId$outboundSchema;
  /** @deprecated use `LearningObjectiveSetLearningObjectiveId$Outbound` instead. */
  export type Outbound = LearningObjectiveSetLearningObjectiveId$Outbound;
}

export function learningObjectiveSetLearningObjectiveIdToJSON(
  learningObjectiveSetLearningObjectiveId:
    LearningObjectiveSetLearningObjectiveId,
): string {
  return JSON.stringify(
    LearningObjectiveSetLearningObjectiveId$outboundSchema.parse(
      learningObjectiveSetLearningObjectiveId,
    ),
  );
}

export function learningObjectiveSetLearningObjectiveIdFromJSON(
  jsonString: string,
): SafeParseResult<
  LearningObjectiveSetLearningObjectiveId,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      LearningObjectiveSetLearningObjectiveId$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'LearningObjectiveSetLearningObjectiveId' from JSON`,
  );
}

/** @internal */
export const LearningObjectiveSet$inboundSchema: z.ZodType<
  LearningObjectiveSet,
  z.ZodTypeDef,
  unknown
> = z.object({
  source: z.string(),
  learningObjectiveIds: z.array(
    z.lazy(() => LearningObjectiveSetLearningObjectiveId$inboundSchema),
  ),
});

/** @internal */
export type LearningObjectiveSet$Outbound = {
  source: string;
  learningObjectiveIds: Array<LearningObjectiveSetLearningObjectiveId$Outbound>;
};

/** @internal */
export const LearningObjectiveSet$outboundSchema: z.ZodType<
  LearningObjectiveSet$Outbound,
  z.ZodTypeDef,
  LearningObjectiveSet
> = z.object({
  source: z.string(),
  learningObjectiveIds: z.array(
    z.lazy(() => LearningObjectiveSetLearningObjectiveId$outboundSchema),
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LearningObjectiveSet$ {
  /** @deprecated use `LearningObjectiveSet$inboundSchema` instead. */
  export const inboundSchema = LearningObjectiveSet$inboundSchema;
  /** @deprecated use `LearningObjectiveSet$outboundSchema` instead. */
  export const outboundSchema = LearningObjectiveSet$outboundSchema;
  /** @deprecated use `LearningObjectiveSet$Outbound` instead. */
  export type Outbound = LearningObjectiveSet$Outbound;
}

export function learningObjectiveSetToJSON(
  learningObjectiveSet: LearningObjectiveSet,
): string {
  return JSON.stringify(
    LearningObjectiveSet$outboundSchema.parse(learningObjectiveSet),
  );
}

export function learningObjectiveSetFromJSON(
  jsonString: string,
): SafeParseResult<LearningObjectiveSet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LearningObjectiveSet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LearningObjectiveSet' from JSON`,
  );
}
