/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Represents the result of updating the student's response to the question in the PowerPath Placement test
 */
export type PlacementUpdateStudentQuestionResponseResult = {
  /**
   * The assessment result object for the question (for debugging)
   */
  questionResult?: any | undefined;
  lessonType: "placement";
};

/** @internal */
export const PlacementUpdateStudentQuestionResponseResult$inboundSchema:
  z.ZodType<
    PlacementUpdateStudentQuestionResponseResult,
    z.ZodTypeDef,
    unknown
  > = z.object({
    questionResult: z.any().optional(),
    lessonType: z.literal("placement"),
  });
/** @internal */
export type PlacementUpdateStudentQuestionResponseResult$Outbound = {
  questionResult?: any | undefined;
  lessonType: "placement";
};

/** @internal */
export const PlacementUpdateStudentQuestionResponseResult$outboundSchema:
  z.ZodType<
    PlacementUpdateStudentQuestionResponseResult$Outbound,
    z.ZodTypeDef,
    PlacementUpdateStudentQuestionResponseResult
  > = z.object({
    questionResult: z.any().optional(),
    lessonType: z.literal("placement"),
  });

export function placementUpdateStudentQuestionResponseResultToJSON(
  placementUpdateStudentQuestionResponseResult:
    PlacementUpdateStudentQuestionResponseResult,
): string {
  return JSON.stringify(
    PlacementUpdateStudentQuestionResponseResult$outboundSchema.parse(
      placementUpdateStudentQuestionResponseResult,
    ),
  );
}
export function placementUpdateStudentQuestionResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<
  PlacementUpdateStudentQuestionResponseResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PlacementUpdateStudentQuestionResponseResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PlacementUpdateStudentQuestionResponseResult' from JSON`,
  );
}
