/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Represents the result of updating the student's response to the question in the PowerPath Quiz lesson
 */
export type QuizUpdateStudentQuestionResponseResult = {
  /**
   * The assessment result object for the question (for debugging)
   */
  questionResult?: any | undefined;
  lessonType: "quiz";
};

/** @internal */
export const QuizUpdateStudentQuestionResponseResult$inboundSchema: z.ZodType<
  QuizUpdateStudentQuestionResponseResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  questionResult: z.any().optional(),
  lessonType: z.literal("quiz"),
});
/** @internal */
export type QuizUpdateStudentQuestionResponseResult$Outbound = {
  questionResult?: any | undefined;
  lessonType: "quiz";
};

/** @internal */
export const QuizUpdateStudentQuestionResponseResult$outboundSchema: z.ZodType<
  QuizUpdateStudentQuestionResponseResult$Outbound,
  z.ZodTypeDef,
  QuizUpdateStudentQuestionResponseResult
> = z.object({
  questionResult: z.any().optional(),
  lessonType: z.literal("quiz"),
});

export function quizUpdateStudentQuestionResponseResultToJSON(
  quizUpdateStudentQuestionResponseResult:
    QuizUpdateStudentQuestionResponseResult,
): string {
  return JSON.stringify(
    QuizUpdateStudentQuestionResponseResult$outboundSchema.parse(
      quizUpdateStudentQuestionResponseResult,
    ),
  );
}
export function quizUpdateStudentQuestionResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<
  QuizUpdateStudentQuestionResponseResult,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      QuizUpdateStudentQuestionResponseResult$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'QuizUpdateStudentQuestionResponseResult' from JSON`,
  );
}
