/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Security = {
  clientID?: string | undefined;
  clientSecret?: string | undefined;
  tokenURL?: string | undefined;
};

/** @internal */
export const Security$inboundSchema: z.ZodType<
  Security,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientID: z.string().optional(),
  clientSecret: z.string().optional(),
  tokenURL: z.string().default(
    "https://alpha-auth-production-idp.auth.us-west-2.amazoncognito.com/oauth2/token",
  ),
});
/** @internal */
export type Security$Outbound = {
  clientID?: string | undefined;
  clientSecret?: string | undefined;
  tokenURL: string;
};

/** @internal */
export const Security$outboundSchema: z.ZodType<
  Security$Outbound,
  z.ZodTypeDef,
  Security
> = z.object({
  clientID: z.string().optional(),
  clientSecret: z.string().optional(),
  tokenURL: z.string().default(
    "https://alpha-auth-production-idp.auth.us-west-2.amazoncognito.com/oauth2/token",
  ),
});

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
export function securityFromJSON(
  jsonString: string,
): SafeParseResult<Security, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Security$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Security' from JSON`,
  );
}
